version: '3'

services:
  dsmauth:
    image: node:dsmauth
    build: ./Authorization
    ports:
      - "3001:3000"
    container_name: dsmauth
    :
    image: node:  
    build: ./Resource
    ports: 
      - "8443:3000"
    container_name:   